version: "3"
services:
  backend:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env
    command: npm run dev
  mongo:
    image: mongo
    env_file:
      - ./.env
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
